import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const copyPlugin = {
    name: 'copy',
    setup(build) {
        build.onEnd(() => {
			// copy to test vaults
			fs.copyFileSync("main.js", "/Users/home/Projects/test-vaults/test vault/.obsidian/plugins/plugin/main.js");
			fs.copyFileSync("manifest.json", "/Users/home/Projects/test-vaults/test vault/.obsidian/plugins/plugin/manifest.json");
			fs.copyFileSync("main.js", "/Users/home/Projects/test-vaults/test vault 2/.obsidian/plugins/plugin/main.js");
			fs.copyFileSync("manifest.json", "/Users/home/Projects/test-vaults/test vault 2/.obsidian/plugins/plugin/manifest.json");
        })
    }
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [copyPlugin]
});



if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
